routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes(
    [
        'register' => false,
        'verify' => true,
        'reset' => false,
        'login' => false,
    ]
);

Route::group(['namespace' => 'Client','middleware'=>'lang'], function () {
    include_route_files(__DIR__ . '/client/');
});
Route::group(['namespace' => 'Admin', 'prefix' => 'manage', 'middleware' => ['auth','check.user','lang']], function () {
    include_route_files(__DIR__ . '/admin/');
});

Route::group(['namespace' => 'Auth', 'prefix' => 'manage'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('manage.getLogin');
    Route::post('/login', 'LoginController@Login')->name('manage.login');
});

Route::get('/login', function () {
    abort(404);
});

//auth with google
Route::group(['namespace' => 'Auth','middleware'=>'lang'], function () {
    include_route_files(__DIR__ . '/auth/');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Category extends Model
{
    use SoftDeletes;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'slug',
        'parent_id',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function childrenCategories()
    {
        return $this->hasMany(Category::class,'parent_id');
    }

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug($value);
    }

    public function scopeWithName($query, $name)
    {
        return $query->where('name', 'LIKE', '%' . $name . '%');
    }

    public function scopeWithSlug($query, $slug)
    {
        return $query->where('slug',$slug);
    }

    public function searchBy($name)
    {
        return $this->withName($name)->with('category')->latest('id')->paginate(10);
    }

    public function findOrFail($id)
    {
        return $this->with('category')->findOrFail($id);
    }

    public function getAllCategoryWhenSoftDelete($searchName)
    {
        return $this->onlyTrashed()->withName($searchName)->with('category')->latest('id')->paginate();
    }

    public function trashDeleteAll()
    {
        return $this->onlyTrashed()->forceDelete();
    }

    public function trashRestoreAll()
    {
        return $this->onlyTrashed()->restore();
    }

    public function trashDeleteBy($id)
    {
        return $this->onlyTrashed()->findOrFail($id)->forceDelete();
    }

    public function trashRestoreBy($id)
    {
        return $this->onlyTrashed()->findOrFail($id)->restore();
    }

    public function products()
    {
        return $this->belongsToMany(Product::class);

    }

    public function findWithSlug($slug)
    {
        return $this->withSlug($slug)->with('products')->first();
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Categories\CreateRequest;
use App\Http\Requests\Categories\UpdateRequest;
use App\Repositories\admin\CategoryRepository;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    protected $categoryRepository;

    public function __construct(CategoryRepository $categoryRepository)
    {

        $this->categoryRepository = $categoryRepository;
    }

    public function index(Request $request)
    {
        $searchName = $request->input('searchKey');
        $categories = $this->categoryRepository->search($searchName);

        return view('admins.categories.index', compact('categories'));
    }

    public function formatRequest(Request $request)
    {
        return $this->categoryRepository->formatRequest($request);
    }

    public function store(CreateRequest $request)
    {
        $data = $this->formatRequest($request);
        $category = $this->categoryRepository->store($data);

        return response()->json([
            'status' => 200,
            'message' => 'Thêm thành công danh mục: ' . $category->name,
            'data' => $category
        ]);
    }

    public function getAll()
    {
        $categories = $this->categoryRepository->get();

        return response()->json([
            'status' => 200,
            'data' => $categories
        ]);
    }

    public function show($id)
    {
        $category=$this->categoryRepository->getById($id);

        return response()->json([
            'status' => 200,
            'data' =>$category,
        ]);
    }

    public function update(UpdateRequest $request, $id)
    {
        $data = $this->formatRequest($request);
        $category = $this->categoryRepository->update($data,$id);

        return response()->json([
            'status' => 200,
            'message' => 'Cập nhật thành công danh mục: ' . $category->name,
            'data' => $category
        ]);
    }

    public function destroy($id)
    {
        $category=$this->categoryRepository->destroy($id);

        return response()->json([
            'status' => 200,
            'message' => 'Xóa  thành công danh mục: ' . $category->name,
            'data' => $category
        ]);
    }

    public function trash(Request $request)
    {
        $searchName=$request->input('searchKey');
        $categories = $this->categoryRepository->trash($searchName);

        return view('admins.categories.trash', compact('categories'));
    }

    public function trashDeleteAll()
    {
        $categories = $this->categoryRepository->trashDeleteAll();

        return view('admins.categories.trash', compact('categories'));
    }

    public function trashRestoreAll()
    {
        $categories = $this->categoryRepository->trashDeleteAll();

        return view('admins.categories.trash', compact('categories'));
    }

    public function trashDelete($id)
    {
        $categories = $this->categoryRepository->trashDelete($id);

        return response()->json([
        'status'=>200,
        'message'=>'Thành công',
    ]);
    }

    public function trashRestore($id)
    {
        $this->categoryRepository->trashRestore($id);

        return response()->json([
           'status'=>200,
           'message'=>'Thành công',
        ]);

    }
}

resources/views/admins/categories/edit.blade.php
<?php

resources/views/admins/categories/form.blade.php
<div class="modal fade" id="newCategoryModal" tabindex="-1" role="dialog" aria-labelledby="newCategoryModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newCategoryModalTitle">Thêm danh mục</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="new-category-form" method="post">
                   @csrf
                    <div class="error-box text-danger">

                    </div>
                    <div class="form-group">
                        <label for="">Tên danh mục</label>
                        <input type="text"  name="name" class="form-control category-name">
                    </div>
                    <div class="form-group">
                        <label for="">Danh mục cha</label>
                        <select name="parent_id" class="category-select-parent form-control">
                            <option value="">--- Chọn danh mục ----</option>
                            <option value="">Không có</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}" {{$category->id==old('parent_id')?'selected':''}}>{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <hr>
                    <div class="form-group text-right">
                        <button type="button" class="btn btn-outline-danger btn-circle"
                                data-dismiss="modal" title="Hủy bỏ"><i
                                class="fas fa-times"></i></button>
                        <button type="button" class="btn btn-outline-primary btn-circle new-category"
                                title="Thêm mới"><i class="fa fa-plus"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="editCategoryModal" tabindex="-1" role="dialog" aria-labelledby="editCategoryModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editCategoryModalTitle">Cập nhật danh mục</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="update-category-form" method="post" >
                    @csrf
                    <div class="error-box text-danger">

                    </div>
                    <div class="form-group">
                        <label for="">Tên danh mục</label>
                        <input type="text"  name="name" class="form-control categoryName">
                    </div>
                    <div>
                        <p class="text-dark">Danh mục cha: <span class="category-parent-name"></span></p>
                    </div>
                    <div class="form-group">
                        <label for="">Thay đổi danh mục cha</label>
                        <select name="parent_id" class="category-select-parent form-control category-parent" style="max-width: 200px">
                            <option value="">--- Chọn danh mục ----</option>
                            <option value="">Không có</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}" {{$category->id==old('parent_id')?'selected':''}}>{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <hr>
                    <div class="form-group text-right">
                        <button type="button" class="btn btn-outline-danger btn-circle"
                                data-dismiss="modal" title="Hủy bỏ"><i
                                class="fas fa-times"></i></button>
                        <button type="button" class="btn btn-outline-primary btn-circle update-category"
                                title="Cập nhật"><i class="fa fa-pencil-alt"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admins/categories/index.blade.php
@extends('admins.layouts.app')

@section('title',__('content.category'))

@section('content')
    <div class="d-flex  mb-4">
        <h1 class="h3 mb-0 text-gray-800">@lang('content.category')</h1>
        @can('new category')
        <button title="@lang('content.add-new') @lang('content.category')" class="btn btn-outline-primary btn-circle ml-2 add-category" data-toggle="modal" data-target="#newCategoryModal">
            <i class="fa fa-plus"></i>
        </button>
        @endcan
        <a title="thùng rác" href="{{route('categories.trash')}}" class="btn btn-outline-danger btn-circle ml-2 " >
            <i class="fa fa-trash"></i>
        </a>
    </div>
    <div class="row d-flex mb-1">
        <div class="search-box">
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" action="{{route('categories.index')}}" method="get">
                <div class="input-group">
                    <input type="text" class="form-control bg-light  small" placeholder="Nhập tên để tìm kiếm..." aria-label="Search" aria-describedby="basic-addon2" name="searchKey" value="{{request()->input('searchKey')}}">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit" title="Tìm kiếm ">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="text-dark">
            <p class="p-2">@lang('content.total'):{{$categories->total()}}</p>
        </div>
    </div>
    <div class="row" id="category">
        <div class="col-12">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>@lang('content.category')</th>
                    <th>@lang('content.parent-category')</th>
                    <th>@lang('content.action')</th>
                </tr>
                </thead>
                <tbody>
                    @foreach( $categories as $category)
                        <tr>
                            <td><strong></strong></td>
                            <td>{{$category->name}}</td>
                            <td>{{$category->category->name??'không có'}}</td>
                            <td>
                                @can('update category')
                                <a href="#"
                                   class="btn btn-circle btn-outline-warning edit-category"
                                   title="Cập nhật thông tin"
                                   edit-id="{{$category->id}}"
                                   data-toggle="modal"
                                   data-target="#editCategoryModal"
                                >
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                                @endcan
                                @can('delete category')
                                <button title="Xóa "
                                        class="btn btn-circle btn-outline-danger delete-category"
                                        delete-id="{{$category->id}}"

                                >
                                    <i class="fas fa-times"></i>
                                </button>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

        </div>
        <div>
            {{$categories->links()}}
        </div>
    </div>
    @include('admins.categories.form')
@endsection

resources/views/admins/categories/trash.blade.php
@extends('admins.layouts.app')

@section('title',' dashboard')

@section('content')
    <div class="d-flex  mb-4">
        <h1 class="h3 mb-0 text-gray-800">Thùng rác của danh mục</h1>
        <a title="Quay lại rang quản lý" href="{{route('categories.index')}}" class="btn btn-outline-primary btn-circle ml-2" >
            <i class="fa fa-backward"></i>
        </a>
{{--        <a title="Phục hồi tất cả" href="{{route('categories.trash.restore.all')}}" class="btn btn-outline-danger btn-circle ml-2" >--}}
{{--            <i class="fa fa-undo"></i>--}}
{{--        </a>--}}
{{--        <a title="Dọn thùng rác" href="{{route('categories.trash.deleteAll')}}" class="btn btn-outline-danger btn-circle ml-2 ">--}}
{{--            <i class="fas fa-eraser"></i>--}}
{{--        </a>--}}
    </div>
    <div class="row d-flex mb-1">
        <div class="search-box">
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" action="{{route('categories.trash')}}" method="get">
                <div class="input-group">
                    <input type="text" class="form-control bg-light  small" placeholder="Nhập tên để tìm kiếm..." aria-label="Search" aria-describedby="basic-addon2" name="searchKey" value="{{request()->input('searchKey')}}">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit" title="Tìm kiếm ">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="text-dark">
            <p class="p-2">Tổng cộng:{{$categories->total()??''}}</p>
        </div>
    </div>
    <div class="row" id="category">
        <div class="col-12">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>Tên danh mục</th>
                    <th>Dannh mục cha</th>
                    <th>Tùy chọn</th>
                </tr>
                </thead>
                <tbody>
                @foreach( $categories as $category)
                    <tr>
                        <td><strong></strong></td>
                        <td>{{$category->name}}</td>
                        <td>{{$category->category->name??'không có'}}</td>
                        <td>
                            <button title="Phục hồi "
                                    class="btn btn-circle btn-outline-danger restore-category"
                                    restore-id="{{$category->id}}"

                            >
                                <i class="fas fa-undo"></i>
                            </button>
                            <button title="Xóa luôn"
                                    class="btn btn-circle btn-outline-danger remove-category"
                                    delete-id="{{$category->id}}"
                            >
                                <i class="fas fa-times"></i>
                            </button>

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        </div>
        <div>
            {{$categories->links()}}
        </div>
    </div>
@endsection